In [93]:
import numpy as np
from numpy import matmul as mt
from sklearn.metrics.pairwise import pairwise_kernels, pairwise_distances

In [94]:
def width(Z):
    """
    Computes the median heuristic for the kernel bandwidth
    """
    dist_mat = pairwise_distances(Z, metric='euclidean')
    width_Z = np.median(dist_mat[dist_mat > 0])
    return width_Z

def generate_kernel(seed):
    np.random.seed(seed)
    K = np.random.randint(5, size=(3, 3))
    K = pairwise_kernels(K, metric='rbf', gamma=0.5 / (width(K) ** 2))
    return K

In [95]:
def centering(K):
    H = np.eye(3) - 1/3 * np.ones(3)
    Kc = H @ K @ H
    return Kc

In [170]:
def first_centering_streitberg_4(Kc, Lc, Mc, Nc):
    length = np.shape(K)[0]

    si = 0
    for i in range(length):
        for j in range(length):
            for k in range(length):
                for l in range(length):
                    p1234_p1234 = Kc[i, k] * Lc[i, k] * Mc[i, k] * Nc[i, k]
                    p1234_p12p34 = Kc[i, k] * Lc[i, k] * Mc[i, j] * Nc[i, j]
                    p1234_p13p24 = Kc[i, k] * Lc[i, j] * Mc[i, k] * Nc[i, j]
                    p1234_p14p23 = Kc[i, k] * Lc[i, j] * Mc[i, j] * Nc[i, k]
                    p12p34_p12p34 = Kc[i, k] * Lc[i, k] * Mc[j, l] * Nc[j, l]
                    p12p34_p13p24 = Kc[i, k] * Lc[i, l] * Mc[j, k] * Nc[j, l]
                    p12p34_p14p23 = Kc[i, k] * Lc[i, l] * Mc[j, l] * Nc[j, k]
                    p13p24_p13p24 = Kc[i, k] * Lc[j, l] * Mc[i, k] * Nc[j, l]
                    p13p24_p14p23 = Kc[i, k] * Lc[j, l] * Mc[i, l] * Nc[j, k]
                    p14p23_p14p23 = Kc[i, k] * Lc[j, l] * Mc[j, l] * Nc[i, k]

                    si = si + p1234_p1234 - 2 * p1234_p12p34 - 2 * p1234_p13p24 - 2 * p1234_p14p23 + p12p34_p12p34 + 2 * p12p34_p13p24 + 2 * p12p34_p14p23+ p13p24_p13p24 + 2 * p13p24_p14p23 + p14p23_p14p23
    return (1/length**4) * si


def second_centering_streitberg_4(Kc, Lc, Mc, Nc, KcLc):
    length = np.shape(K)[0]

    si = 0
    for i in range(length):
        for j in range(length):
            for k in range(length):
                for l in range(length):
                    p1234_p1234 = KcLc[i, k] * Mc[i, k] * Nc[i, k]
                    p1234_p13p24 = Kc[i, k] * Lc[i, j] * Mc[i, k] * Nc[i, j]
                    p1234_p14p23 = Kc[i, k] * Lc[i, j] * Mc[i, j] * Nc[i, k]
                    p13p24_p13p24 = Kc[i, k] * Lc[j, l] * Mc[i, k] * Nc[j, l]
                    p13p24_p14p23 = Kc[i, k] * Lc[j, l] * Mc[i, l] * Nc[j, k]
                    p14p23_p14p23 = Kc[i, k] * Lc[j, l] * Mc[j, l] * Nc[i, k]
                    si = si + p1234_p1234 - 2 * p1234_p13p24 - 2 * p1234_p14p23 + p13p24_p13p24 + 2 * p13p24_p14p23 + p14p23_p14p23
    return (1/length**4) * si

In [174]:
seed = 40
K = generate_kernel(seed)
Kc = centering(K)

L = generate_kernel(seed+1)
Lc = centering(L)

M = generate_kernel(seed+2)
Mc = centering(M)

N = generate_kernel(seed+3)
Nc = centering(N)

KcLc = centering(Kc * Lc)

In [175]:
first_centering_streitberg_4(Kc, Lc, Mc, Nc)

0.0012844184853450188

In [176]:
second_centering_streitberg_4(Kc, Lc, Mc, Nc, KcLc)

-0.00025396791722191936

In [183]:
list_of_lists = [K[0] for _ in range(3)]

In [184]:
list_of_lists

[array([1.        , 0.52578802, 0.60653066]),
 array([1.        , 0.52578802, 0.60653066]),
 array([1.        , 0.52578802, 0.60653066])]

In [191]:
K

array([[1.        , 0.52578802, 0.60653066],
       [0.52578802, 1.        , 0.75147729],
       [0.60653066, 0.75147729, 1.        ]])

In [186]:
dict = {'a':1, 'b':2} 

In [189]:
list(dict.values())

[1, 2]