In [1]:
import numpy as np
from numpy import matmul as mt

In [2]:
H = np.eye(3) - 1/3 * np.ones(3)
print(H)

[[ 0.66666667 -0.33333333 -0.33333333]
 [-0.33333333  0.66666667 -0.33333333]
 [-0.33333333 -0.33333333  0.66666667]]


In [13]:
K = np.random.randint(5, size=(3, 3))
K = (K + K.T)/2
print(K)

[[3.  4.  3. ]
 [4.  4.  0.5]
 [3.  0.5 3. ]]


In [14]:
L = np.random.randint(5, size=(3, 3))
L = (L + L.T)/2
print(L)

[[1. 0. 2.]
 [0. 0. 1.]
 [2. 1. 3.]]


In [17]:
Kc = mt(mt(H, K),H)
print(Kc)

[[-0.88888889  0.61111111  0.27777778]
 [ 0.61111111  1.11111111 -1.72222222]
 [ 0.27777778 -1.72222222  1.44444444]]


In [46]:
Lc = mt(mt(H, L),H)
print(Lc)

[[-0.33333333  0.66666667 -0.33333333]
 [ 0.66666667 -2.33333333  1.66666667]
 [-0.33333333  1.66666667 -1.33333333]]


In [48]:
def centering(k):
    H = np.eye(3) - 1/3 * np.ones(3)
    return mt(mt(H, k),H)

In [51]:
centering(Kc*Lc)

array([[-0.81481481,  0.18518519,  0.62962963],
       [ 0.18518519, -0.25925926,  0.07407407],
       [ 0.62962963,  0.07407407, -0.7037037 ]])

In [53]:
Kc*Lc

array([[-0.25925926,  0.07407407,  0.2962963 ],
       [ 0.07407407, -1.03703704, -0.92592593],
       [ 0.2962963 , -0.92592593, -1.92592593]])

In [55]:
mt(Kc, Lc)

array([[ 0.11111111, -1.22222222,  1.11111111],
       [ 0.44444444, -1.88888889,  1.44444444],
       [-0.55555556,  3.11111111, -2.55555556]])

In [16]:
H @ K @ H

array([[-0.88888889,  0.61111111,  0.27777778],
       [ 0.61111111,  1.11111111, -1.72222222],
       [ 0.27777778, -1.72222222,  1.44444444]])

In [1]:
def gridfunc(func):
    def wrapper():
        sums = 0
        for i in range(3):
            for j in range(3):
                results.append(func(col))
        return sums
    return wrapper

@gridfunc
def foo(x):
    return x+1

grid = [[1,2,3,],[4,5,6],[7,8,9]]
results = foo(grid)

In [7]:
import numpy as np
grid = np.array([[1,2,3,],[4,5,6],[7,8,9]])

In [9]:
grid[0,0]

1

In [15]:
length = np.shape(grid)[0]
sums = 0
for i in range(length):
    for j in range(length):
        sums = sums + grid[i,j]*grid[i,j]
sums = 1/(length**8) * sums

In [20]:
index = 'i'

In [21]:
index.strip('\"')

'i'